import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { localServices } from "@/lib/local-services";
import { gallery } from "@/lib/content";
import { PageIntro, Button, DesignCard } from "@/components/ui";
import { seo, whatsapp, site, JsonLd } from "@/lib/site";
export const dynamicParams = false;
export function generateStaticParams(){return localServices.map(s=>({service:s.slug}));}
export async function generateMetadata({params}:{params:Promise<{service:string}>}){const {service}=await params;const s=localServices.find(s=>s.slug===service);return s?seo(s.title,s.description,`/${s.slug}`,s.image?`/images/${s.image}.webp`:undefined):{};}
export default async function LocalService({params}:{params:Promise<{service:string}>}){const {service}=await params;const s=localServices.find(s=>s.slug===service);if(!s)notFound();const design=gallery.find(d=>d.slug===s.image);const related=gallery.filter(d=>s.slug.startsWith('traditional')?d.category==='Traditional Wear':d.category==='Special Occasions').slice(0,3);return <><PageIntro eyebrow="WEAR MEGA-E · AGONA SWEDRU" title={s.title}><p>{s.description}</p></PageIntro><section className="wrap section article-body">{design&&<Image src={design.images[0].src} alt={design.images[0].alt} width={design.images[0].width} height={design.images[0].height} style={{maxHeight:550,objectFit:'contain',margin:'0 auto 40px'}} sizes="(max-width:760px) 90vw, 700px"/>}{s.sections.map(([title,copy])=><section key={title}><h2>{title}</h2><p>{copy}</p></section>)}<h2>Start your enquiry.</h2><p>Wear Mega-E is based in Agona Swedru, Ghana. Call <a href="tel:+233261939295">0261939295</a> or message us to confirm directions and appointment availability.</p><Button href={whatsapp(`Hello Wear Mega-E, I would like to enquire about ${s.title}.`)}>Discuss your outfit</Button><p style={{marginTop:24}}><Link className="text-link" href="/contact">Contact the studio ↗</Link></p><p><Link href="/blog/choosing-fashion-designer-agona-swedru">Read our guide to choosing a fashion designer in Agona Swedru ↗</Link></p></section>{s.image&&<section className="wrap section"><h2>Explore design inspiration.</h2><div className="design-grid">{related.map(d=><DesignCard key={d.slug} design={d}/>)}</div></section>}<section className="wrap section"><h2>More women’s fashion services.</h2><div className="filters">{localServices.filter(x=>x.slug!==s.slug).map(x=><Link className="text-link" key={x.slug} href={`/${x.slug}`}>{x.title} ↗</Link>)}</div></section><JsonLd data={{'@context':'https://schema.org','@type':'Service',name:s.title,description:s.description,url:site.url+'/'+s.slug,areaServed:{'@type':'City',name:'Agona Swedru'},provider:{'@type':'Organization',name:site.name,url:site.url,telephone:site.international}}}/></>}
